import { generateRandomUser } from '../../support/helpers/data-generator'

describe('Checkout - Guest Checkout', () => {
  beforeEach(() => {
    cy.clearCookies()
    cy.clearLocalStorage()
  })

  it('TC-003a: Flow Add to cart tanpa login - Satu produk dari dashboard', () => {
    cy.visit('https://demo.evershop.io/')
    cy.wait(500)
    cy.contains('h3', 'Stainless Steel Thermos - Yellow').scrollIntoView()
    cy.wait(500)
    cy.contains('h3', 'Stainless Steel Thermos - Yellow').click({ force: true })
    cy.wait(1000)
    cy.url().should('include', '/accessories/stainless-steel-thermos-yellow')
    cy.contains('button', 'White').click({ force: true })
    cy.wait(500)
    cy.get('[name="qty"]').clear({ force: true }).type('1', { force: true })
    cy.wait(500)
    cy.contains('button', 'ADD TO CART').click({ force: true })
    cy.wait(1000)
    cy.get('#mui-5').should('be.visible')
    cy.xpath("//button[normalize-space()='Checkout']").click({ force: true })
    cy.wait(1000)
    cy.url().should('include', '/checkout')

    const guest = generateRandomUser()
    const fullName = `${guest.firstName} ${guest.lastName}`

    cy.get('[name="contact.email"]').type(guest.email, { force: true })
    cy.wait(500)
    cy.get('[id="field-shippingAddress.full_name"]').scrollIntoView().type(fullName, { force: true })
    cy.wait(500)
    cy.xpath("//input[@id='field-shippingAddress.telephone']").type(guest.phone, { force: true })
    cy.wait(500)
    cy.get('[id="field-shippingAddress.address_1"]').type(guest.address, { force: true })
    cy.wait(500)
    cy.scrollTo('bottom')
    cy.wait(500)
    cy.get('[name="shippingAddress.address_1"]').type(guest.address, { force: true })
    cy.wait(500)
    cy.get('[id="field-shippingAddress.city"]').type(guest.city, { force: true })
    cy.wait(500)
    cy.xpath("//button[@id='field-shippingAddress.country']").click({ force: true })
    cy.wait(500)
    cy.get('div.flex.flex-1.whitespace-nowrap').contains('United States').click({ force: true })
    cy.wait(500)
    cy.xpath("//button[@id='field-shippingAddress.province']").click({ force: true })
    cy.wait(500)
    cy.xpath("//div[position()=2]/div[position()=1]/div[position()=1]/div[position()=3]/div[position()=1]").click({ force: true })
    cy.wait(500)
    cy.get('[name="shippingAddress.postcode"]').type(guest.zipCode, { force: true })
    cy.wait(1500)

    cy.scrollTo('bottom')
    cy.wait(1000)
    // Shipping method
    cy.get('[role="radio"], input[type="radio"]').eq(0).click({ force: true })
    cy.wait(1000)
    cy.scrollTo('bottom')
    cy.wait(1000)
    // Payment Method
    cy.get('form').find('div').contains('Cash On Delivery').click({ force: true })
    cy.wait(1000)
    cy.scrollTo('bottom')
    cy.wait(1000)
    cy.xpath('//div/div[4]/button').click({ force: true })
    cy.wait(2000)
    
    cy.contains('span', 'Checkout success').should('be.visible')
    cy.wait(500)
    cy.get('button[type="button"][title="CONTINUE SHOPPING"]').click({ force: true })
    cy.wait(500)
  })

  it('TC-003b: checkout multiple variant dari dashboard', () => {
    cy.visit('https://demo.evershop.io/')
    cy.wait(500)
    cy.contains('h3', 'Stainless Steel Thermos - Yellow').scrollIntoView()
    cy.wait(500)
    cy.contains('h3', 'Stainless Steel Thermos - Yellow').click({ force: true })
    cy.wait(1000)
    cy.url().should('include', '/accessories/stainless-steel-thermos-yellow')
    
    // First variant
    cy.contains('button', 'White').click({ force: true })
    cy.wait(500)
    cy.get('[name="qty"]').clear({ force: true }).type('1', { force: true })
    cy.wait(500)
    cy.contains('button', 'ADD TO CART').click({ force: true })
    cy.wait(1000)
    cy.xpath("//div[@data-slot='sheet-overlay']", { timeout: 10000 }).click({ force: true })
    cy.wait(1500)
    
    // Second variant
    cy.contains('button', /(Yellow|Black|Green|Red)/).click({ force: true })
    cy.wait(500)
    cy.get('[name="qty"]').clear({ force: true }).type('1', { force: true })
    cy.wait(500)
    cy.contains('button', 'ADD TO CART').click({ force: true })
    cy.wait(1000)
    
    cy.get('#mui-5').should('be.visible')
    cy.xpath("//button[normalize-space()='Checkout']").click({ force: true })
    cy.wait(1000)
    cy.url().should('include', '/checkout')

    const guest = generateRandomUser()
    const fullName = `${guest.firstName} ${guest.lastName}`

    cy.get('[name="contact.email"]').type(guest.email, { force: true })
    cy.wait(500)
    cy.get('[id="field-shippingAddress.full_name"]').scrollIntoView().type(fullName, { force: true })
    cy.wait(500)
    cy.xpath("//input[@id='field-shippingAddress.telephone']").type(guest.phone, { force: true })
    cy.wait(500)
    cy.get('[id="field-shippingAddress.address_1"]').type(guest.address, { force: true })
    cy.wait(500)
    cy.scrollTo('bottom')
    cy.wait(500)
    cy.get('[name="shippingAddress.address_1"]').type(guest.address, { force: true })
    cy.wait(500)
    cy.get('[id="field-shippingAddress.city"]').type(guest.city, { force: true })
    cy.wait(500)
    cy.xpath("//button[@id='field-shippingAddress.country']").click({ force: true })
    cy.wait(500)
    cy.get('div.flex.flex-1.whitespace-nowrap').contains('United States').click({ force: true })
    cy.wait(500)
    cy.xpath("//button[@id='field-shippingAddress.province']").click({ force: true })
    cy.wait(500)
    cy.xpath("//div[position()=2]/div[position()=1]/div[position()=1]/div[position()=3]/div[position()=1]").click({ force: true })
    cy.wait(500)
    cy.get('[name="shippingAddress.postcode"]').type(guest.zipCode, { force: true })
    cy.wait(1500)

    cy.scrollTo('bottom')
    cy.wait(1000)
    cy.get('[role="radio"], input[type="radio"]').eq(0).click({ force: true })
    cy.wait(1000)
    cy.scrollTo('bottom')
    cy.wait(1000)
    cy.get('form').find('div').contains('Cash On Delivery').click({ force: true })
    cy.wait(1000)
    cy.scrollTo('bottom')
    cy.wait(1000)
    cy.xpath('//div/div[4]/button').click({ force: true })
    cy.wait(2000)
    
    cy.contains('span', 'Checkout success').should('be.visible')
  })

  it('TC-003c: checkout multiple variant multiple produk dari dashboard', () => {
    cy.visit('https://demo.evershop.io/')
    cy.wait(500)
    
    cy.contains('h3', 'Stainless Steel Thermos - Yellow').scrollIntoView()
    cy.wait(500)
    cy.contains('h3', 'Stainless Steel Thermos - Yellow').click({ force: true })
    cy.wait(1000)
    cy.url().should('include', '/accessories/stainless-steel-thermos-yellow')
    cy.contains('button', 'White').click({ force: true })
    cy.wait(500)
    cy.get('[name="qty"]').clear({ force: true }).type('1', { force: true })
    cy.wait(500)
    cy.contains('button', 'ADD TO CART').click({ force: true })
    cy.wait(1000)
    cy.xpath("//div[@data-slot='sheet-overlay']", { timeout: 10000 }).click({ force: true })
    cy.wait(1500)
    cy.contains('button', /(Yellow|Black|Green|Red)/).click({ force: true })
    cy.wait(500)
    cy.get('[name="qty"]').clear({ force: true }).type('1', { force: true })
    cy.wait(500)
    cy.contains('button', 'ADD TO CART').click({ force: true })
    cy.wait(1000)
    
    cy.contains('a', 'Home').click({ force: true })
    cy.wait(1000)
    cy.url().should('eq', 'https://demo.evershop.io/')
    
    cy.contains('h3', 'Modern Ceramic Vase - Green').scrollIntoView()
    cy.wait(500)
    cy.contains('h3', 'Modern Ceramic Vase - Green').click({ force: true })
    cy.wait(1000)
    cy.url().should('include', '/accessories/modern-ceramic-vase-green')
    cy.contains('button', 'White').click({ force: true })
    cy.wait(500)
    cy.get('[name="qty"]').clear({ force: true }).type('1', { force: true })
    cy.wait(500)
    cy.contains('button', 'ADD TO CART').click({ force: true })
    cy.wait(1000)
    cy.xpath("//div[@data-slot='sheet-overlay']", { timeout: 10000 }).click({ force: true })
    cy.wait(1500)
    cy.contains('button', /(Yellow|Black|Green|Red)/).click({ force: true })
    cy.wait(500)
    cy.get('[name="qty"]').clear({ force: true }).type('1', { force: true })
    cy.wait(500)
    cy.contains('button', 'ADD TO CART').click({ force: true })
    cy.wait(1000)

    cy.get('#mui-5').should('be.visible')
    cy.xpath("//button[normalize-space()='Checkout']").click({ force: true })
    cy.wait(1000)
    cy.url().should('include', '/checkout')

    const guest = generateRandomUser()
    const fullName = `${guest.firstName} ${guest.lastName}`

    cy.get('[name="contact.email"]').type(guest.email, { force: true })
    cy.wait(500)
    cy.get('[id="field-shippingAddress.full_name"]').scrollIntoView().type(fullName, { force: true })
    cy.wait(500)
    cy.xpath("//input[@id='field-shippingAddress.telephone']").type(guest.phone, { force: true })
    cy.wait(500)
    cy.get('[id="field-shippingAddress.address_1"]').type(guest.address, { force: true })
    cy.wait(500)
    cy.scrollTo('bottom')
    cy.wait(500)
    cy.get('[name="shippingAddress.address_1"]').type(guest.address, { force: true })
    cy.wait(500)
    cy.get('[id="field-shippingAddress.city"]').type(guest.city, { force: true })
    cy.wait(500)
    cy.xpath("//button[@id='field-shippingAddress.country']").click({ force: true })
    cy.wait(500)
    cy.get('div.flex.flex-1.whitespace-nowrap').contains('United States').click({ force: true })
    cy.wait(500)
    cy.xpath("//button[@id='field-shippingAddress.province']").click({ force: true })
    cy.wait(500)
    cy.xpath("//div[position()=2]/div[position()=1]/div[position()=1]/div[position()=3]/div[position()=1]").click({ force: true })
    cy.wait(500)
    cy.get('[name="shippingAddress.postcode"]').type(guest.zipCode, { force: true })
    cy.wait(1500)

    cy.scrollTo('bottom')
    cy.wait(1000)
    cy.get('[role="radio"], input[type="radio"]').eq(0).click({ force: true })
    cy.wait(1000)
    cy.scrollTo('bottom')
    cy.wait(1000)
    cy.get('form').find('div').contains('Cash On Delivery').click({ force: true })
    cy.wait(1000)
    cy.scrollTo('bottom')
    cy.wait(1000)
    cy.xpath('//div/div[4]/button').click({ force: true })
    cy.wait(2000)
    
    cy.contains('span', 'Checkout success').should('be.visible')
  })

  it('TC-003d: User checkout tanpa login barang dari Category page', () => {
    cy.visit('https://demo.evershop.io/')
    cy.wait(500)
    
    // category page finding has an overflow issue, so use force true
    cy.get('a[href="/accessories"]').contains('View Collection').click({ force: true })
    cy.wait(1000)
    cy.url().should('eq', 'https://demo.evershop.io/accessories')
    
    cy.contains('h3', 'Modern Ceramic Vase - White').scrollIntoView()
    cy.wait(500)
    cy.contains('h3', 'Modern Ceramic Vase - White').click({ force: true })
    cy.wait(1000)
    cy.contains('button', 'White').click({ force: true })
    cy.wait(500)
    cy.get('[name="qty"]').clear({ force: true }).type('1', { force: true })
    cy.wait(500)
    cy.contains('button', 'ADD TO CART').click({ force: true })
    cy.wait(1000)
    cy.xpath("//div[@data-slot='sheet-overlay']", { timeout: 10000 }).click({ force: true })
    cy.wait(1500)
    cy.contains('button', /(Yellow|Black|Green|Red)/).click({ force: true })
    cy.wait(500)
    cy.get('[name="qty"]').clear({ force: true }).type('1', { force: true })
    cy.wait(500)
    cy.contains('button', 'ADD TO CART').click({ force: true })
    cy.wait(1000)
    cy.xpath("//div[@data-slot='sheet-overlay']", { timeout: 10000 }).click({ force: true })
    cy.wait(1500)
    
    cy.contains('a', 'Accessories').click({ force: true })
    cy.wait(1000)
    cy.url().should('eq', 'https://demo.evershop.io/accessories')
    
    cy.contains('h3', 'Ceramic Coffee Cup - Yellow').scrollIntoView()
    cy.wait(500)
    cy.contains('h3', 'Ceramic Coffee Cup - Yellow').click({ force: true })
    cy.wait(1000)
    cy.url().should('eq', 'https://demo.evershop.io/accessories/ceramic-coffee-cup-yellow')
    cy.contains('button', 'White').click({ force: true })
    cy.wait(500)
    cy.get('[name="qty"]').clear({ force: true }).type('1', { force: true })
    cy.wait(500)
    cy.contains('button', 'ADD TO CART').click({ force: true })
    cy.wait(1000)
    cy.xpath("//div[@data-slot='sheet-overlay']", { timeout: 10000 }).click({ force: true })
    cy.wait(1500)
    cy.contains('button', /(Yellow|Black|Green|Red)/).click({ force: true })
    cy.wait(500)
    cy.get('[name="qty"]').clear({ force: true }).type('1', { force: true })
    cy.wait(500)
    cy.contains('button', 'ADD TO CART').click({ force: true })
    cy.wait(1000)
    
    cy.xpath("//button[normalize-space()='View Cart (4)']").click({ force: true })
    cy.wait(1000)
    
    cy.contains('td', 'Ceramic Coffee Cup - White').parent('tr').should('exist')
    cy.contains('td', 'Ceramic Coffee Cup - Black').parent('tr').should('exist')
    cy.contains('td', 'Modern Ceramic Vase - White').parent('tr').should('exist')
    cy.contains('td', 'Modern Ceramic Vase - Black').parent('tr').should('exist')
    
    for (let i = 0; i < 5; i++) {
      cy.get('table tbody tr').eq(0).contains('+').click({ force: true })
      cy.wait(500)
      cy.get('table tbody tr').eq(1).contains('+').click({ force: true })
      cy.wait(500)
    }
    
    for (let i = 0; i < 2; i++) {
      cy.get('table tbody tr').eq(0).contains('-').click({ force: true })
      cy.wait(1000)
      cy.get('table tbody tr').eq(1).contains('-').click({ force: true })
      cy.wait(1000)
    }

    
    cy.get('table tbody tr').eq(1).find('a').contains('Remove').click({ force: true })
    cy.wait(1000)
    
    cy.get('button[type="button"][title="CHECKOUT"]').click({ force: true })
    cy.wait(1000)
    cy.url().should('include', '/checkout')
    
    cy.contains('Modern Ceramic Vase').should('be.visible')
    
    const guest = generateRandomUser()
    const fullName = `${guest.firstName} ${guest.lastName}`

    cy.get('[name="contact.email"]').type(guest.email, { force: true })
    cy.wait(500)
    cy.get('[id="field-shippingAddress.full_name"]').scrollIntoView().type(fullName, { force: true })
    cy.wait(500)
    cy.xpath("//input[@id='field-shippingAddress.telephone']").type(guest.phone, { force: true })
    cy.wait(500)
    cy.get('[id="field-shippingAddress.address_1"]').type(guest.address, { force: true })
    cy.wait(500)
    cy.scrollTo('bottom')
    cy.wait(500)
    cy.get('[name="shippingAddress.address_1"]').type(guest.address, { force: true })
    cy.wait(500)
    cy.get('[id="field-shippingAddress.city"]').type(guest.city, { force: true })
    cy.wait(500)
    cy.xpath("//button[@id='field-shippingAddress.country']").click({ force: true })
    cy.wait(500)
    cy.get('div.flex.flex-1.whitespace-nowrap').contains('United States').click({ force: true })
    cy.wait(500)
    cy.xpath("//button[@id='field-shippingAddress.province']").click({ force: true })
    cy.wait(500)
    cy.xpath("//div[position()=2]/div[position()=1]/div[position()=1]/div[position()=3]/div[position()=1]").click({ force: true })
    cy.wait(500)
    cy.get('[name="shippingAddress.postcode"]').type(guest.zipCode, { force: true })
    cy.wait(1500)

    cy.scrollTo('bottom')
    cy.wait(1000)
    cy.get('[role="radio"], input[type="radio"]').eq(0).click({ force: true })
    cy.wait(1000)
    cy.scrollTo('bottom')
    cy.wait(1000)
    cy.get('form').find('div').contains('Cash On Delivery').click({ force: true })
    cy.wait(1000)
    cy.scrollTo('bottom')
    cy.wait(1000)
    cy.xpath('//div/div[4]/button').click({ force: true })
    cy.wait(2000)
    
    cy.contains('span', 'Checkout success').should('be.visible')
  })
})
